### ISSUE TITLE
Doesn't update right away

### ISSUE THREAD

**Issue by RedHatter** [duncanthrax/roccat-vulcan#8]
When I start `roccat-vulcan` the keyboard doesn't change. I have to turn the fx nob down to get it to update.

When I start `roccat-vulcan` it ouputs

    ROCCAT Vulcan for Linux [github.com/duncanthrax/roccat-vulcan]
    Effect Color Table (change these with -c option)
    colorIdx    R      G      B  Desc
    ------------------------------------------------
    0           0      0    119  Base keyboard color (dark blue)
    1        2303      0   -255  Typing color, initial key (over-red, under-blue)
    2        2303      0   -143  Typing color, first neighbor key
    3        2303      0      0  Typing color, second neighbor key
    4         187      0    204  Ghost typing color, initial key
    5         153      0    187  Ghost typing color, first neighbor key
    6          85      0    170  Ghost typing color, second neighbor key
    7           0      0      0  (null)
    8           0      0      0  (null)
    9           0      0      0  (null)
    open_device(1e7d, 3098): LED interface at USB path 0001:0007:03
    open_device(1e7d, 3098): CTRL interface at /dev/hidraw1

After I turn the nob it outputs

    Using event input device /dev/input/event9
    Using event input device /dev/input/event7
    Using event input device /dev/input/event5
    Using event input device /dev/input/event8
    Using event input device /dev/input/event6

**Comment by nomego** [comment]
Same here, and then I have to leave it running. As far as I remember, it would exit on earlier versions?

**Comment by SpiritCroc** [comment]
Happened to me too that nothing changes until the fx-knob was used, this was fixed for me by updating the firmware of the keyboard.

@nomego For the typing effect, it needs to be running since this is software controlled. Previously, from what I've seen, it would create it's own background process, but this was changed to prefer the start-stop-daemon way described in the README in commit https://github.com/duncanthrax/roccat-vulcan/commit/888f5a41003a1e92b9063da241f64d021800f3c7.

**Comment by nomego** [comment]
Ah ok, thanks!
Going to have to look at fw update then, thanks!

**Comment by RedHatter** [comment]
@SpiritCroc Was right. Once I updated the firmware the issue disappeared.
